import os
import argparse
from datetime import datetime
import ollama
import re
from tqdm import tqdm
from obsidian_manager import ObsidianGardener  # Import Ogrodnika

# --- KONFIGURACJA ---
OBSIDIAN_VAULT_PATH = os.path.join(os.getcwd(), "Education")
OLLAMA_MODEL = "bielik"
CHUNK_SIZE = 6000
OVERLAP = 500

# --- PRECYZYJNY PROMPT ---
SYSTEM_PROMPT = """
Jesteś Ekspertem Technicznym i Analitykiem Cyberbezpieczeństwa. Tworzysz precyzyjną dokumentację techniczną w formacie Obsidian Markdown.

Twoje zadanie: Przeanalizuj podany transkrypt wideo/szkolenia i stwórz zwięzłą, techniczną notatkę.

WYMAGANIA FORMATOWANIA:
1. Używaj TYLKO nagłówków H2 (##) dla głównych sekcji. Nie używaj H1 (tytuł jest w metadanych).
2. Kluczowe pojęcia, narzędzia i technologie pogrubiaj (np. **nmap**, **SQL Injection**).
3. WSZYSTKIE komendy, ścieżki plików, fragmenty kodu i logi umieszczaj w blokach kodu:
   ```bash
   nmap -sV 192.168.1.1
   ```
4. Ignoruj całkowicie dygresje, żarty, powitania ("Cześć", "Dajcie suba") i lanie wody.
5. Pisz w stylu bezosobowym, technicznym (np. "Należy wykonać skan...", "Podatność polega na...").
6. Jeśli fragment nie zawiera konkretnej wiedzy, pomiń go.

CELEM JEST DOKŁADNOŚĆ. Nie zmyślaj. Opieraj się tylko na tekście.
"""

def clean_filename(title):
    title = title.lower()
    title = re.sub(r'[^\w\s-]', '', title)
    return re.sub(r'[\s_-]+', '-', title).strip('-')

def create_chunks(text, chunk_size=CHUNK_SIZE, overlap=OVERLAP):
    chunks = []
    start = 0
    text_len = len(text)
    while start < text_len:
        end = start + chunk_size
        chunk = text[start:end]
        chunks.append(chunk)
        start += chunk_size - overlap
    return chunks

def generate_title_and_summary(full_text_sample):
    prompt = "Jesteś bibliotekarzem. Na podstawie tego fragmentu stwórz: 1. Krótki techniczny tytuł (max 6 słów, bez znaków specjalnych). 2. Jedno zdanie streszczenia."
    try:
        response = ollama.chat(
            model=OLLAMA_MODEL, 
            messages=[{'role': 'system', 'content': prompt}, {'role': 'user', 'content': full_text_sample[:2000]}],
            options={'temperature': 0.3} # Precyzja
        )
        return response['message']['content']
    except Exception as e:
        print(f"[!] Błąd generowania tytułu: {e}")
        return "Szkolenie Cybersec AutoNote"

def process_transcript(file_path):
    print(f"[*] Wczytywanie transkrypcji: {file_path}")
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            full_text = f.read()
    except FileNotFoundError:
        print("[!] Plik nie istnieje.")
        return

    print("[*] Analiza wstępna...")
    meta_info = generate_title_and_summary(full_text)
    
    if meta_info:
        lines = meta_info.split('\n')
        raw_title = lines[0].replace('Tytuł:', '').strip()
        safe_title = clean_filename(raw_title)[:60]
    else:
        safe_title = "unknown-training"
    
    chunks = create_chunks(full_text)
    print(f"[*] Przetwarzanie {len(chunks)} fragmentów (Model: {OLLAMA_MODEL}, Temp: 0.2)...")

    full_notes = []
    
    for i, chunk in enumerate(tqdm(chunks, desc="Analiza AI", unit="blok")):
        try:
            response = ollama.chat(
                model=OLLAMA_MODEL, 
                messages=[{'role': 'system', 'content': SYSTEM_PROMPT}, {'role': 'user', 'content': chunk}],
                options={'temperature': 0.2} # Niski parametr dla faktów
            )
            note_part = response['message']['content']
            full_notes.append(f"\n## Część {i+1}\n{note_part}")
        except Exception as e:
            full_notes.append(f"\n> [!ERROR] Błąd przetwarzania fragmentu {i+1}: {e}")

    # Zapis
    final_path = save_note(safe_title, meta_info, full_notes)
    
    # --- FAZA OGRODNIKA (POST-PROCESSING) ---
    if final_path:
        print(f"[*] Uruchamiam Ogrodnika (ObsidianGardener) dla: {final_path}")
        gardener = ObsidianGardener(OBSIDIAN_VAULT_PATH)
        success, msg = gardener.process_file(final_path)
        if success:
            print(f"[+] Ogrodnik: {msg}")
        else:
            print(f"[!] Ogrodnik zgłosił błąd: {msg}")

def save_note(title, intro, notes_list):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    date_prefix = datetime.now().strftime("%Y-%m-%d")
    filename = f"{date_prefix}-{title}.md"
    filepath = os.path.join(OBSIDIAN_VAULT_PATH, filename)
    
    joined_notes = "\n".join(notes_list)

    content = f"""---
created: {timestamp}
tags:
  - auto-generated
  - education
  - transkrypt
status: to-review
---

# {title}

> **Meta:** {intro}

---
{joined_notes}

---
*Generated by AI Bridge (Precision Mode)*
"""
    
    if not os.path.exists(OBSIDIAN_VAULT_PATH):
        os.makedirs(OBSIDIAN_VAULT_PATH)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"\n[SUCCESS] Zapisano surową notatkę: {filepath}")
    return filepath

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("file", help="Ścieżka do pliku transkrypcji")
    parser.add_argument("--output", help="Folder docelowy", default=OBSIDIAN_VAULT_PATH)
    args = parser.parse_args()
    
    if args.output:
        OBSIDIAN_VAULT_PATH = args.output
    
    process_transcript(args.file)
